### ISSUE TITLE
配置文件问题

### ISSUE THREAD

**Issue by clothesack** [ZimoLoveShuang/auto-submit#1]
大佬，配置文件的网站是*.cpdaily.com/iap 吗，网站从哪里获取呢

**Comment by ZimoLoveShuang** [comment]
抓包就有了哈，可能我这个不适合你们学校，但思路是一样的，都是金智公司做的



---原始邮件---
发件人: "SuperAlan"<notifications@github.com&gt;
发送时间: 2020年4月3日(周五) 下午3:55
收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZimoLoveShuang/auto-submit] 配置文件问题 (#1)




 
大佬，配置文件的网站是*.cpdaily.com/iap 吗，网站从哪里获取呢

**Comment by ZimoLoveShuang** [comment]
solve
