### ISSUE TITLE
ssl pining问题

### ISSUE THREAD

**Issue by Itswag** [ZimoLoveShuang/auto-submit#3]
不懂就问，大佬用那种方式破除的证书验证

**Comment by ZimoLoveShuang** [comment]
hook，具体来说就是在逍遥安卓Android4.4模拟器上，通过xposed框架加载justtrustme模块hook掉验证函数，使它永远返回为true



---原始邮件---
发件人: "Sr"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 晚上8:27
收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ZimoLoveShuang/auto-submit] ssl pining问题 (#3)




 
不懂就问，大佬用那种方式破除的证书验证

**Comment by Itswag** [comment]
这个我前几天试了，app直接秒退了，现在我准备再尝试一下

**Comment by Itswag** [comment]
> hook，具体来说就是在逍遥安卓Android4.4模拟器上，通过xposed框架加载justtrustme模块hook掉验证函数，使它永远返回为true
> […](#)
> ---原始邮件--- 发件人: "Sr"<notifications@github.com&gt; 发送时间: 2020年4月7日(周二) 晚上8:27 收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [ZimoLoveShuang/auto-submit] ssl pining问题 (#3) 不懂就问，大佬用那种方式破除的证书验证 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

这个我前几天试了，app直接秒退了，现在我准备再尝试一下

**Comment by Itswag** [comment]
这个我前几天试了，app直接秒退了，现在我准备再尝试一下 @ZimoLoveShuang

**Comment by ZimoLoveShuang** [comment]
我当时抓的时候试了很多模拟器，包括，mumu，夜神，蓝蝶，等等等，最后试了逍遥安卓，然后APP闪退，不过提示我用4.4试一下，我就抱着试一试的态度，最后成功了



---原始邮件---
发件人: "Sr"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 晚上8:57
收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"子墨"<461009747@qq.com&gt;;
主题: Re: [ZimoLoveShuang/auto-submit] ssl pining问题 (#3)




 
这个我前几天试了，app直接秒退了，现在我准备再尝试一下 @ZimoLoveShuang

**Comment by Itswag** [comment]
> 我当时抓的时候试了很多模拟器，包括，mumu，夜神，蓝蝶，等等等，最后试了逍遥安卓，然后APP闪退，不过提示我用4.4试一下，我就抱着试一试的态度，最后成功了
> […](#)
> ---原始邮件--- 发件人: "Sr"<notifications@github.com&gt; 发送时间: 2020年4月7日(周二) 晚上8:57 收件人: "ZimoLoveShuang/auto-submit"<auto-submit@noreply.github.com&gt;; 抄送: "Mention"<mention@noreply.github.com&gt;;"子墨"<461009747@qq.com&gt;; 主题: Re: [ZimoLoveShuang/auto-submit] ssl pining问题 (#3) 这个我前几天试了，app直接秒退了，现在我准备再尝试一下 @ZimoLoveShuang — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


![QQ截图20200407211033](https://user-images.githubusercontent.com/39112652/78673285-8079e380-7914-11ea-8f23-62cce7d90911.png)
我记起来了，上次就是这样，换了几个历史版本了，再次裂开哈哈

**Comment by ZimoLoveShuang** [comment]
> > 我当时抓的时候试了很多模拟器，包括，mumu，夜神，蓝蝶，等等等，最后试了逍遥安卓，然后APP闪退，不过提示我用4.4试一下，我就抱着试一试的态度，最后成功了
> > […](#)
> > ---原始邮件--- 发件人: "Sr"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年4月7日(周二) 晚上8:57 收件人: "ZimoLoveShuang/auto-submit"<[auto-submit@noreply.github.com](mailto:auto-submit@noreply.github.com)>; 抄送: "Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>;"子墨"<[461009747@qq.com](mailto:461009747@qq.com)>; 主题: Re: [ZimoLoveShuang/auto-submit] ssl pining问题 (#3) 这个我前几天试了，app直接秒退了，现在我准备再尝试一下 @ZimoLoveShuang — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> ![QQ截图20200407211033](https://user-images.githubusercontent.com/39112652/78673285-8079e380-7914-11ea-8f23-62cce7d90911.png)
> 我记起来了，上次就是这样，换了几个历史版本了，再次裂开哈哈

你要先把已经安装了的今日校园卸载了，再安装，我也不知道为什么，但是这样操作就安装成功了，估计是apk版本冲突吧

**Comment by Itswag** [comment]
@ZimoLoveShuang 这是新建的模拟器，可能是模拟器更新改了什么东西，准备下载个模拟器的历史版本了

**Comment by Itswag** [comment]
@ZimoLoveShuang 搞定了，我用的老版本逍遥模拟器，现在可以抓到包了😄

**Comment by ZimoLoveShuang** [comment]
> @ZimoLoveShuang 搞定了，我用的老版本逍遥模拟器，现在可以抓到包了😄

看来确实是逍遥安卓模拟器更新了

**Comment by ZimoLoveShuang** [comment]
solve

**Comment by bcahlit** [comment]
> @ZimoLoveShuang 搞定了，我用的老版本逍遥模拟器，现在可以抓到包了😄

请问用的那个版本的？谢谢
