### ISSUE TITLE
错误是请提交正确的信息收集信息

### ISSUE THREAD

**Issue by wenjunjiecn** [ZimoLoveShuang/auto-submit#30]
可以登录可以查看表单，但是就是不能正确提交表单
2020-12-30 19:26:07 必填问题5：本人健康状况是否正常？
2020-12-30 19:26:07 答案5：身体健康，正常
2020-12-30 19:26:07 填写问卷成功。。。
2020-12-30 19:26:07 正在自动提交。。。
2020-12-30 19:26:07 自动提交失败。。。
2020-12-30 19:26:07 错误是请提交正确的信息收集信息
2020-12-30 19:26:08 邮件发送失败

**Comment by SnowMeteors** [comment]
我也是

**Comment by wenjunjiecn** [comment]
问题解决，在post提交表单的时候，需要多添加一个"uaIsCpadaily":True  验证字段

**Comment by SnowMeteors** [comment]
> 问题解决，在post提交表单的时候，需要多添加一个"uaIsCpadaily":True 验证字段

兄弟，能否说清楚一点？

**Comment by MrBlessing** [comment]
这个字段加在哪里啊

**Comment by shunzhao** [comment]
> > 问题解决，在post提交表单的时候，需要多添加一个"uaIsCpadaily":True 验证字段
> 
> 兄弟，能否说清楚一点？

添加到submitCollectorForm函数中的body字典最后一行就可以了。

**Comment by shunzhao** [comment]
> 这个字段加在哪里啊

https://github.com/ZimoLoveShuang/auto-submit/issues/30#issuecomment-753991679

**Comment by wenjunjiecn** [comment]
第263-264行    params = {"formWid": formWid, "address": address, "collectWid": collectWid, "schoolTaskWid": schoolTaskWid,
              "form": form,"uaIsCpadaily":True}

**Comment by wenjunjiecn** [comment]
> > 问题解决，在post提交表单的时候，需要多添加一个"uaIsCpadaily":True 验证字段
> 
> 兄弟，能否说清楚一点？

第263-264行 params = {"formWid": formWid, "address": address, "collectWid": collectWid, "schoolTaskWid": schoolTaskWid,
"form": form,"uaIsCpadaily":True}

**Comment by wenjunjiecn** [comment]
> > 这个字段加在哪里啊
> 
> [#30 (comment)](https://github.com/ZimoLoveShuang/auto-submit/issues/30#issuecomment-753991679)

第263-264行 params = {"formWid": formWid, "address": address, "collectWid": collectWid, "schoolTaskWid": schoolTaskWid,
"form": form,"uaIsCpadaily":True}

**Comment by wenjunjiecn** [comment]
> 这个字段加在哪里啊

第263-264行 params = {"formWid": formWid, "address": address, "collectWid": collectWid, "schoolTaskWid": schoolTaskWid,
"form": form,"uaIsCpadaily":True}

**Comment by MrBlessing** [comment]
> > > 问题解决，在post提交表单的时候，需要多添加一个"uaIsCpadaily":True 验证字段
> > 
> > 
> > 兄弟，能否说清楚一点？
> 
> 第263-264行 params = {"formWid": formWid, "address": address, "collectWid": collectWid, "schoolTaskWid": schoolTaskWid,
> "form": form,"uaIsCpadaily":True}

我还以为是ualsCpadaily 这里面的大写的i和小写的l完全不分啊，谢谢解答
