### ISSUE TITLE
这个还能用吗

### ISSUE THREAD

**Issue by fishUPs** [ZimoLoveShuang/auto-submit#45]
找了一圈，似乎api全挂了。。。有大佬现在还能用吗

**Comment by ZirrorDmage** [comment]
看了一下今天的签到，查寝没问题，其他部分就不晓得了。问这种问题还不如直接上手一下来得快

**Comment by fishUPs** [comment]
运行通用流程的时候，本地执行login.py时候提示ModuleNotFoundError: No module named 'pyDes'
