### ISSUE TITLE
关于模拟登录api

### ISSUE THREAD

**Issue by jshxy** [ZimoLoveShuang/auto-submit#6]
Readme里“教务系统登录爬虫”的那个连接挂掉了，没太搞得明白模拟登录api的地址应该怎么抓，目前抓到了login_url，iOS端今日校园。

**Comment by ZimoLoveShuang** [comment]
1. 模拟登陆api是我免费提供的，由于涉及支付接口，已经闭源
2. 如果你能保证用户名和密码正确的话，你需要把login_url配置成你抓到的
3. 至于needcaptcha_url，captcha_url 是用来针对验证码识别的，三次输错密码会出现验证码，防君子不防小人，只要不出现验证码，可以不填
4. 完成后配置cpdaily相关的内容即可食用我的脚本
5. 总结：login_url：配置成你的，然后配置user，配置capdaily_api（抓包发现接口），配置capdaily（表单的默认选项）
6. enjoy it

**Comment by jshxy** [comment]
这样说的话我在二次开发的时候可以忽略模拟登陆api的配置了吧？谢谢您耐心的解答，感谢！

**Comment by ZimoLoveShuang** [comment]
是的，不过不建议这样，白嫖是个不好的习惯，过段时间，等空了，我会开源模拟登录的API，你可以在那个项目的基础上二次开发
