### ISSUE TITLE
老哥 今日校园 定位加照片的这种可以提交吗？

### ISSUE THREAD

**Issue by wyap-echo** [ZimoLoveShuang/auto-submit#8]

**Comment by ZimoLoveShuang** [comment]
只要是在今日校园提交`收集表`都通用，但我看你这个描述，你们的任务应该是`签到`吧，签到需要小改一下脚本

**Comment by wyap-echo** [comment]
对的 是签到，在消息列表里有一个辅导员通知 点进去在里面签到

**Comment by ZimoLoveShuang** [comment]
如果你有能力自己完成脚本，可以参考我的[`auto-sign`](https://github.com/ZimoLoveShuang/auto-sign)项目；如果没有，欢迎捐赠后联系我，Q：461009747，我可以帮你
